### ISSUE TITLE
Chat logs are not filtered to be line unique.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#1]
BMP Beta 6
21 connected bards used for sake of stress testing

Chat logs are not being filtered to appear only once and line unique for the same timestamp. This is causing sentences someone says to appear numerous times for every connected bard on the client.
![link](https://i.imgur.com/ry00Oar.png)

Similarly these are other chat issues I noticed but not sure of the already known and state of the feature still being worked on.
* New chat lines don't automatically force the window to the bottom when they come in. Same with changing tabs at the top. You have to manually scroll to the very bottom for every new message.
* There is no visible scroll bar.
* There is no timestamp.
* Player world names are not properly characterized, causing their world to appear mixed with their last name. Likewise, there is no space after the colon for the message.

**Comment by GiR-Zippo** [comment]
Note for me: Limit the chat to the host bard will keep the chat clean.

**Comment by GiR-Zippo** [comment]
- chatbox is now like the old BMP1.x
- only the HostBard will flood this box :)
- done (I guess)
