### ISSUE TITLE
BMP crashes when you click the - or x buttons in the playlist window without a song loaded.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#10]
BMP Beta 7
21 connected bards used for sake of stress testing

BMP crashes when you click the ``-`` or ``x`` buttons in the playlist window without a song loaded.
![link](https://i.imgur.com/giN9ZDB.png)

The icons should probably be named to New, Load, Save also instead of N, L, S as to not confuse people with assuming it may be Loop or Shuffle/Skip. And perhaps X to Delete also so people don't assume it's close playlist and have their entire saved playlist removed without confirming.

**Comment by GiR-Zippo** [comment]
- crash was caused by null pointer.
(is fixed at the next release)
- Changed the button naming and added tooltips
![grafik](https://user-images.githubusercontent.com/324273/147857344-306c6f06-afb0-402d-ad95-b5b75afaaa4b.png)
