### ISSUE TITLE
Application name is incorrect & missing icons.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#2]
BMP Beta 7
21 connected bards used for sake of stress testing

![link](https://i.imgur.com/txEEhZl.png)

Application doesn't seem to be named BardMusicPlayer, is missing the icon, & has a blank title for processes running under it (1 blank with classic UI, 2 blank + 1 named with built-in custom UI).

**Comment by GiR-Zippo** [comment]
- fixed
![grafik](https://user-images.githubusercontent.com/324273/147858282-2cc104ba-bd68-452f-b77c-790e3276aa11.png)
