### ISSUE TITLE
GPU usage increases exponentially the faster you scroll through the chat window.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#3]
BMP Beta 7
21 connected bards used for sake of stress testing

I noticed that BardMusicPlayer's GPU usage goes up exponentially the faster you scroll in the chat window. By default doing nothing, BMP idles at 0% gpu usage. Scrolling down at a moderate speed, the usage spikes to 1%. Unlocking my scroll wheel on my mouse and scrolling down, I managed to hit 6.5% of my gpu (2080ti) being used just to render chat logs. The faster I scroll, the more gpu usage the logs use.

![link](https://i.imgur.com/gRa6tXY.png)

Is there a reason for this? Is it pulling the data from each client every time logs are scrolled? Should chat logs be cached in a local file or memory? I have no idea why it would use the GPU that much, rendering text seems simple unless it was doing display updates too frequently?

**Comment by GiR-Zippo** [comment]
I think this one has something to do how wpf is handling the refresh.

I'll try investigate this, cuz there is no cache or something else behind this.
The chat event is a fire and forget function, msg comes in and will be appended to the textbox. After this all other things are handled by the .net routines.

**Comment by GiR-Zippo** [comment]
Fix (temp): Now I'm using DeferredScrolling. This wouldn't update the box every single pixel.
