### ISSUE TITLE
Siren load button does not function.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#4]
BMP Beta 7
21 connected bards used for sake of stress testing

![link](https://i.imgur.com/V2he8zO.png)

Siren (which should probably be named Preview for players to identify it more easily) does not seem to function. Clicking the load button does not open any explorer window to load a song for previewing.

**Comment by GiR-Zippo** [comment]
Siren is working now. Forgot to remove a ifdef.
