### ISSUE TITLE
Loading a song does not automatically separate performers across all available tracks.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#5]
BMP Beta 7
21 connected bards used for sake of stress testing

![link](https://i.imgur.com/R0Uen4J.png)

Loading a song does not automatically separate performers across all available tracks. Tested with Local Orchestra checked and unchecked. Upon loading any Duet - Octet song, all local bards default to T1. You have to manually specify each track for every performer. Fortunately the set track # does not change when changing songs. 

I believe this functionality is present in BMP 1.x.

**Comment by Meowchestra** [comment]
Likewise, track count can be set in the negative. Getting all available tracks from the midi so the player has a known available range to use and reserving T0 for "all tracks" like BMP 1.x would probably be ideal.

![link](https://i.imgur.com/VA0ezmK.png)

You also have to specify T with the number, can't just have a number if you manually enter the track.

**Comment by GiR-Zippo** [comment]
- tracknumbers will spread across all the bards loading the first performance (or until you uncheck and recheck the box)
- no negative tracknumbers
- single digit positive tracknumbers can be typed in all others characters will be ignored
I guess it's a done :)
