### ISSUE TITLE
Manual octave shift & note density heatmap are missing from the default UI.

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#6]
BMP Beta 7
21 connected bards used for sake of stress testing

Unlike BMP 1.x, octave shifting & the note density heatmap seems to be missing from the default UI. You are unable to manually shift octaves on individual tracks unless they are done so by track name with +/-, i.e. ``Piano+1``. I assume some other things might be missing in the classic UI compared to custom one too.

**Comment by GiR-Zippo** [comment]
- heatmap will be added later, sorry for that
- octave shifting via +/- in the trackname is supported
- manual octave shifting will be there in the next version

**Comment by GiR-Zippo** [comment]
- done (heatmap will be added later)
