### ISSUE TITLE
Scaling the classic UI window larger does not scale the individual windows

### ISSUE THREAD

**Issue by Meowchestra** [GiR-Zippo/BMP2.0-Test#8]
BMP Beta 7
21 connected bards used for sake of stress testing

Scaling the classic UI window larger does not scale the individual windows. It creates empty space instead of making the individual containers larger (which may have scroll bars) to show more. i.e. More performers, more chat logs, a larger playlist, etc.

![link](https://i.imgur.com/Gvw2L0d.png)

**Comment by GiR-Zippo** [comment]
- done :P
